# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pm_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pm_proto.proto',
  package='',
  serialized_pb=_b('\n\x0epm_proto.proto\x1a\x0cnanopb.proto\"\xbb\x02\n\x07pmproto\x12#\n\x04type\x18\x01 \x02(\x0e\x32\x15.pmproto.Message_type\x12\x0b\n\x03seq\x18\x02 \x01(\r\x12\x0c\n\x04\x66ile\x18\x03 \x01(\x0c\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x12\n\nfixture_id\x18\x14 \x01(\r\x12\x11\n\tcolorspec\x18\x15 \x01(\x07\x12\x11\n\tintensity\x18\x16 \x01(\r\x12\x10\n\x08\x63uestack\x18\x1e \x01(\x07\x12\n\n\x02go\x18\x1f \x01(\x08\"\x86\x01\n\x0cMessage_type\x12\x08\n\x04PING\x10\x00\x12\x08\n\x04PONG\x10\x01\x12\x0b\n\x07VERSION\x10\x02\x12\x07\n\x03\x41\x43K\x10\x03\x12\t\n\x05PATCH\x10\n\x12\t\n\x05STACK\x10\x0b\x12\n\n\x06\x43ONFIG\x10\x0c\x12\x0b\n\x07TRIGGER\x10\r\x12\x0b\n\x07\x46IXTURE\x10\x14\x12\x08\n\x04LOAD\x10\x1e\x12\x06\n\x02GO\x10\x1f')
  ,
  dependencies=[nanopb_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PMPROTO_MESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Message_type',
  full_name='pmproto.Message_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PING', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PONG', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VERSION', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACK', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PATCH', index=4, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STACK', index=5, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONFIG', index=6, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER', index=7, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIXTURE', index=8, number=20,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOAD', index=9, number=30,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GO', index=10, number=31,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=214,
  serialized_end=348,
)
_sym_db.RegisterEnumDescriptor(_PMPROTO_MESSAGE_TYPE)


_PMPROTO = _descriptor.Descriptor(
  name='pmproto',
  full_name='pmproto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='pmproto.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq', full_name='pmproto.seq', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file', full_name='pmproto.file', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='pmproto.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fixture_id', full_name='pmproto.fixture_id', index=4,
      number=20, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='colorspec', full_name='pmproto.colorspec', index=5,
      number=21, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='intensity', full_name='pmproto.intensity', index=6,
      number=22, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cuestack', full_name='pmproto.cuestack', index=7,
      number=30, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='go', full_name='pmproto.go', index=8,
      number=31, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PMPROTO_MESSAGE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=348,
)

_PMPROTO.fields_by_name['type'].enum_type = _PMPROTO_MESSAGE_TYPE
_PMPROTO_MESSAGE_TYPE.containing_type = _PMPROTO
DESCRIPTOR.message_types_by_name['pmproto'] = _PMPROTO

pmproto = _reflection.GeneratedProtocolMessageType('pmproto', (_message.Message,), dict(
  DESCRIPTOR = _PMPROTO,
  __module__ = 'pm_proto_pb2'
  # @@protoc_insertion_point(class_scope:pmproto)
  ))
_sym_db.RegisterMessage(pmproto)


# @@protoc_insertion_point(module_scope)
